// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__-n9obnfG2LOJA15KFebXeIDhUJaLrA',
    appId: '1:469693488242:web:8b26a249be43d21893f6eb',
    messagingSenderId: '469693488242',
    projectId: 'fixit-d718f',
    authDomain: 'fixit-d718f.firebaseapp.com',
    storageBucket: 'fixit-d718f.firebasestorage.app',
    measurementId: 'G-WXJZHH24XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAswh_MroBQ5nOEEk_c_1_cJUtn9lEu0',
    appId: '1:469693488242:android:56aa6b373e12952893f6eb',
    messagingSenderId: '469693488242',
    projectId: 'fixit-d718f',
    storageBucket: 'fixit-d718f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBOJ93FBHAA9qhPoq-e-vJtDrbRfXrNU',
    appId: '1:469693488242:ios:48831b0d56b77bff93f6eb',
    messagingSenderId: '469693488242',
    projectId: 'fixit-d718f',
    storageBucket: 'fixit-d718f.firebasestorage.app',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBOJ93FBHAA9qhPoq-e-vJtDrbRfXrNU',
    appId: '1:469693488242:ios:48831b0d56b77bff93f6eb',
    messagingSenderId: '469693488242',
    projectId: 'fixit-d718f',
    storageBucket: 'fixit-d718f.firebasestorage.app',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA__-n9obnfG2LOJA15KFebXeIDhUJaLrA',
    appId: '1:469693488242:web:b36473b555323f3d93f6eb',
    messagingSenderId: '469693488242',
    projectId: 'fixit-d718f',
    authDomain: 'fixit-d718f.firebaseapp.com',
    storageBucket: 'fixit-d718f.firebasestorage.app',
    measurementId: 'G-T694LDSL91',
  );

}
  